### ISSUE TITLE
Отсутствуют записи о картах и операциях в DBeaver

### ISSUE THREAD

**Issue by DispUrr** [DispUrr/AQADiploma#2]
**Шаги по воспроизведению**
1. Склонировать [репозиторий](https://github.com/DispUrr/AQADiploma);
2. Запустить Docker в консоли Idea командой: docker-compose up -d
3. Запустить приложение в консоли Idea: командой java -jar aqa-shop.jar
4. Создать MySQL соединение в DBeaver 
![изображение](https://user-images.githubusercontent.com/78687520/163353276-2c9677f5-eca4-45c4-8420-1178087754b7.png)
5. Проверить соединение, нажав кнопку **Тест соединения...**, и убедиться, что соединение установлено 
![изображение](https://user-images.githubusercontent.com/78687520/163353687-d528d87b-4239-4f0f-bb35-267987d08b0b.png)

**Ожидаемый результат**
В DBeaver появляется наша БД, в таблице payment_entity инфо об APPROVED и DECLINED картах.

**Фактический результат**
Фактически таблицы пустые, при проверке соединения (ПКМ на localhost -> Проверить соединение) 
![изображение](https://user-images.githubusercontent.com/78687520/163354724-43cdd50d-7774-451d-9524-451ed4b2b411.png)
В правом нижнем углу приложения появляется попап, что Datasource was invalidated 
![изображение](https://user-images.githubusercontent.com/78687520/163355000-61764f99-9090-4739-b6d2-39ca1e23f61c.png)
При этом тест с асертом на статус карты проходит.

**Окружение**
Windows 10 Pro x64
IntelliJ IDEA 2021.1 (Community Edition)
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Java 11.0.10
Docker Desktop 4.6.1 (76265)
DBeaver 22.0.2.202204041542

**Comment by Vladanna** [comment]
Здравствуйте,

Вы проверяете таблицу после теста или после того все подняли?
Есть предположение что когда каждый раз проект поднимается база чистится
Так же нет у вас шага очистки базы после тестов или перед?

**Comment by DispUrr** [comment]
Добрый день!
Смотрю после поднятия контейнеров.
То есть, последовательность такая:
1. docker-compose up в консоли проекта
2. Настраиваю подключение к MySQL в DBeaver 
![изображение](https://user-images.githubusercontent.com/78687520/166911779-e1614b78-2a32-4c91-aed9-c273453e2c1d.png)
3. При этом в консоли проекта появляются такие записи: mbind: Operation not permitted
![изображение](https://user-images.githubusercontent.com/78687520/166911926-b9862ce0-e239-44a2-98b6-9012fd3e88b7.png)
Не могу разобраться, в чём проблема, переподключение не помогает.

**Comment by DispUrr** [comment]
Проблема в отсутствии записей в DBeaver - некорректный запуск приложения.
Необходимо строго указывать необходимую БД.
В случае с MySQL запуск приложения необходимо производить командой:
java -Dspring.datasource.url=jdbc:mysql://localhost:3306/app -jar aqa-shop.jar
